apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: mlops
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - name: pg
      port: 5432
      targetPort: pg
      protocol: TCP
  selector:
    app.kubernetes.io/name: postgres
