apiVersion: v1
kind: Service
metadata:
  name: feast-feature-server
  namespace: mlops
  labels:
    app.kubernetes.io/name: feast-feature-server
    app.kubernetes.io/component: feature-store
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 6566
      targetPort: http
      protocol: TCP
    - name: ui
      port: 8888
      targetPort: ui
      protocol: TCP
  selector:
    app.kubernetes.io/name: feast-feature-server
