apiVersion: v1
kind: ConfigMap
metadata:
  name: ksops-cmp-cm
  namespace: argocd
data:
  ksops.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: ksops
    spec:
      version: v1.0
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build --enable-alpha-plugins --enable-exec"]
      discover:
        fileName: "*kustomization.yaml*"
