# Dữ liệu secret này là ví dụ cho Age Key SOPS. 
# Bạn phải tự tạo bí mật thực tế trên Cluster với nội dung Private Key.
# Lệnh gợi ý:
# age-keygen -o age.agekey
# kubectl create secret generic sops-age-key -n argocd --from-file=keys.txt=age.agekey

apiVersion: v1
kind: Secret
metadata:
  name: sops-age-key
  namespace: argocd
type: Opaque
stringData:
  keys.txt: |
    # created: 2026-03-16T11:18:31+07:00
    # public key: age173tf49eq2m2zm8w88tk65529yqnlqfs2wgm7nv9jj2yhst397dfszu8try
    AGE-SECRET-KEY-16X9EDXQKYDJ4SEESYHH455ASJPRKFYHHAN9SWZP5LRM9XL6PEDRQY5NVHW