apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-app

generators:
  - secret-generator.yaml

secretGenerator:
  - name: my-app-secret
    files:
      - secret.yaml=secret.enc.yaml