apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: ENC[AES256_GCM,data:wB6itc4PYK0=,iv:qTppVOWvyVs3arQLui5pmh2uHN1WN53XD3p8fN+mIYQ=,tag:fDdgx2GLL1CjuVC/Qzv3/Q==,type:str]
    password: ENC[AES256_GCM,data:o1a4JZttLAdMOYCDsSRr0w==,iv:nxkOuybRu2ubjfYvX3gHfxZart9oMuNIGiAt0nb1LIU=,tag:pP80uqspqJuwBtOjb6XW1w==,type:str]
sops:
    age:
        - recipient: age173tf49eq2m2zm8w88tk65529yqnlqfs2wgm7nv9jj2yhst397dfszu8try
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeDdKaEdrbUQyOWZudm1w
            aXdURmMxb0NBUWZCTnJPVjJNQkhCNjQ2UEdNCkljbmdCakpBaE9qK0NNZlpuV0lK
            aCs0ZThFVXVJcTJEQjVVZDl3SGpCd2sKLS0tIFpyQnBLaVk5VGdJYjVZWjYybHFw
            WGNOTS9OcWNYQUxzL2MxWm5oM1pod0EKdJGIQO9XnDKol1PSrP5E2qCMnDSILThi
            mPGXFM/II8GKp5NSPcUBV0S5YoznGSQQvh1pXuceo1oBADhi7rj+7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T07:38:23Z"
    mac: ENC[AES256_GCM,data:1JFZnZ4p6ajarH7VzVW/frlTPLNySv+kzIz+VtCev+rHb0bd8keDZp+7GUcoBjrU5qHfE2YO4fz+lDnFcHf0OEib5OsVb+O7/AaKQ5dVTACeGCJMjGRhscMwUipWNIUVC3vkiz4K3I/eiHcty21uzBJg3khzIvLrVPfNU1Z3raQ=,iv:tCwHNMn34zhS75XDaF4AQvVSsH5iQaSzlKd7pBAtVW8=,tag:0+wa4c0e0qO2xqyf3PHHpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
