apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  # MinIO credentials
  - name: minio-secret
    literals:
      - MINIO_ROOT_USER=mlops-admin
      - MINIO_ROOT_PASSWORD=changeme-minio-secret-2024
  # PostgreSQL credentials
  - name: postgres-secret
    literals:
      - POSTGRES_PASSWORD=changeme-postgres-secret-2024
      - MLFLOW_DB_PASSWORD=changeme-mlflow-db-2024
      - AIRFLOW_DB_PASSWORD=changeme-airflow-db-2024
      - FEAST_DB_PASSWORD=changeme-feast-db-2024
  # Redis credentials
  - name: redis-secret
    literals:
      - REDIS_PASSWORD=changeme-redis-secret-2024
  # MLflow S3-compatible env (points to MinIO)
  - name: mlflow-s3-secret
    literals:
      - AWS_ACCESS_KEY_ID=mlops-admin
      - AWS_SECRET_ACCESS_KEY=changeme-minio-secret-2024
      - MLFLOW_S3_ENDPOINT_URL=http://minio.mlops.svc.cluster.local:9000
