apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    releaseName: argocd
    version: 7.7.1
    includeCRDs: true
    valuesFile: values.yaml

resources:
  - patches/tailscale-ingress.yaml
  - patches/ksops-cmp-cm.yaml
  - patches/sops-age-key-secret.yaml