apiVersion: v1
kind: Service
metadata:
  name: model-serving
  namespace: mlops
  labels:
    app.kubernetes.io/name: model-serving
    app.kubernetes.io/component: serving
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: model-serving
