apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlops
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/component: experiment-tracking
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: mlflow
