apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: mlops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # storageClassName: local-path  # Uncomment and set to your StorageClass
