apiVersion: v1
kind: Secret
metadata:
    name: nginx-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:+E+rYF4=,iv:jTzKCOa8ISQIfqAVxGz3XVVmMt5KT8125lSGTIMeqJc=,tag:z2+HHCqEDU+1NjLg3q3BUQ==,type:str]
    password: ENC[AES256_GCM,data:Cg9xjqk=,iv:CdzDPWPtAMHkKU1f+sZekSYN3krb5EHoth2S0CljViU=,tag:pvStpdzgsJVUvTlINNkaFQ==,type:str]
sops:
    age:
        - recipient: age173tf49eq2m2zm8w88tk65529yqnlqfs2wgm7nv9jj2yhst397dfszu8try
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSTRqMGFXK3BZVmVlckt6
            V2NSaFMzNS9OUUs4c0dkMmNLcDRVcjgrdVg4ClJWU0ZaUVgwN0FoWllGNTJpK2hC
            WjVTUkFiQXNwSGVqaGYySjRhL0xTVUUKLS0tIEU0R3dPYm5YTVVvTW05dlFIOXg3
            cDBkYXRVR3lTRFA1REtwM244T2xzbEUKtj4fvwKWvRPYXuM8fLlYWi4UH9bNcY04
            gIST4qtJIJ13yfkKkPBH32fwgF27VgsjNMux6jO8d+Lk2vIpv5i0og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T11:33:13Z"
    mac: ENC[AES256_GCM,data:N7JPj9kTbDPVCAI6iVmnwA03dajLxRB6ZYruz5miZ+rmsbCCUF5kvQe3yKv9LxRjOI5+JD4tc3pkA70AnJXcOMOw8A6JkY0AbTlYKwFfWv0V1IICdwUqshHeHRMG0W/g3GAWTBW/MWQ+8blqHuldsCYHMhhYn1GRyxrCeGgxpRM=,iv:btDqb1fAn26tXT0UtFM9QYvNTLOUPFdkbYadLl66X74=,tag:2SJWo7/OWti7TDNS0/HqQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
