apiVersion: v1
kind: Secret
metadata:
    name: nginx-secret
type: Opaque
data:
    username: ENC[AES256_GCM,data:l1J3OIc=,iv:rErYNaAyypOlFvQuH7w8sfB7Cb5h2e9u7W/B2SovFOM=,tag:jBMa7HtslLiNBnqAWX8/cQ==,type:str]
    password: ENC[AES256_GCM,data:8UlJvKc=,iv:DfwZFE1FaaAAgID9gyd3wuDlgC4leFoylm24GDP1eyA=,tag:aatGDMM49PeQP4p2ugi08Q==,type:str]
sops:
    age:
        - recipient: age173tf49eq2m2zm8w88tk65529yqnlqfs2wgm7nv9jj2yhst397dfszu8try
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2U210VEdCYzhqb1RiQ0lo
            Sk5hSGFHOW90UWNLeWoyVEhoMmdrTzJNdmhJCmxiSDBjeFVyeG5mNkczcEszSVFZ
            M0NTVDZQNkZlU2h4dG5sSnM3MmVUK1UKLS0tIFFwMG5zN05rNDJSS1F5WWtWWFlK
            eFRhaS93NHN4TnFTZmtEc2lDQkxBZjAKsJcG+Rd/D5qG81WFewXgApTfmbuYNZHT
            gReUxiRshuysRCFSIwEIjBbZ/0ko/1c0hKcR1u1ldHObNhmOBfz5yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T09:29:16Z"
    mac: ENC[AES256_GCM,data:a69pnHN/JqRx7YsvFWzMYSlqwFBA4nNEOiAf1/xslIQ7GbftlzUx2Sb6aZnYc4MswPQ3qPk8orQTBUY0WIWVlKGPM64hluKqbgiRn/1p3H1riEn3hhlWmwyhhJf4izygMoHzNLyTVUy7lgZavC6AWMmUkZrGsM0vkkgoYWFM1+k=,iv:uW1M0J5WmtU+ql8snDGFp5rkjEHP+QuSma/mLUMWDpo=,tag:RaUxCgjQRARkK9bczgx6Jw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
