apiVersion: v1
kind: Secret
metadata:
  name: mariadb-cert
  namespace: ns-db
type: Opaque
stringData:
  server.cas: |
    -----BEGIN CERTIFICATE-----
    ... (replaced by kustomize generator plugin or from-file)
    -----END CERTIFICATE-----
